### ISSUE TITLE
DfE-Statements-of-SEN-and-EHC-Plans-England

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-disability#1]
- [x] Create Jenkins job (in Jenkins).
- [x] Create a Jenkinsfile.
- [x] Figure out landing page.
- [x] Create main.py and check scraper works.
- [x] Determine eventual Tidy data column names and add to `info.json`.
- [x] Map column names to codelists (existing and newly required), adding mapping to `info.json`.
- [x] Add definition to `reference/columns.csv`
- [x] Add newly required codelists (under `reference/codelists`) and add info to `reference/codelists-metadata.json`
- [x] Add component definitions to `reference/components.csv`
- [x] Write a transformation to Tidy CSV and output metadata `dataset.trig` and schema. 
     - [x]  Draft
     - [x]  Finalised

**Comment by RedWalters** [comment]
Notes on this data set say that DMs are going through the spreadsheets; is this still in progress or on hold?

Also there are 3 Excel spreadsheets:

- National tables: Special educational needs in England - January 2019
- LA tables: Special educational needs in England - January 2019
- Additional tables: Special educational needs in England - January 2019

Are these all being used or is that one of the things that the DMs are going through?

**Comment by MartynBSpooner** [comment]
Same landing page as Special Education - investigation required.

**Comment by MartynBSpooner** [comment]
For BA Team to estimate size and complexity.

**Comment by MartynBSpooner** [comment]
No scraper for LP.

**Comment by VTula2000** [comment]
Landing page https://www.gov.uk/government/collections/statistics-special-educational-needs-sen

Second in Contents list data source page :
https://www.gov.uk/government/collections/statistics-special-educational-needs-sen#statements-of-special-educational-needs-(sen)-and-education,-health-and-care-(ehc)-plans

Direct data page: https://www.gov.uk/government/statistics/statements-of-sen-and-ehc-plans-england-2019

**Comment by VTula2000** [comment]
Tidy data validated
https://ci.floop.org.uk/job/GSS_data/job/Disability/job/DfE-Statements-of-SEN-and-EHC-Plans-England/
need to fix concept errors
