### ISSUE TITLE
DWP-Family-Resources-Survey-Carer

### ISSUE THREAD

**Issue by LPerryman** [GSS-Cogs/family-disability#10]
- [x]  Create Jenkins job (in Jenkins).
- [x]  Create a Jenkinsfile.
- [x] Figure out landing page.
- [x] Create main.py and check scraper works.
- [x] Determine eventual Tidy data column names and add to info.json.
- [x] Map column names to codelists (existing and newly required), adding mapping to info.json.
- [x] Add definition to reference/columns.csv
- [x] Add newly required codelists (under reference/codelists) and add info to reference/codelists-metadata.json
- [x]  Add component definitions to reference/components.csv
- [x] Write a transformation to Tidy CSV and output metadata `dataset.trig` and schema. 
     - [x]  Draft
     - [ ]  Finalised

**Comment by LPerryman** [comment]
Sheet 5_1: ignoring table at bottom, Millions of informal carers for now.
Sheet 5_7: ignoring tale at bottom, Person cared for, Percentage of informal carers for now.
Sheet 5_7: hidden formulas with white colour font in cells F32 and F33, finding a way of selecting a range of cells to get around this

**Comment by ajtucker** [comment]
The observation.csv tables need a `Measure Type` column. I've added a new measure, `Percentage of People`, but will need others.

I've added a dimension `FRS Age Group`, as the age groups are specific to the FRS data. We'll need a corresponding codelist.

**Comment by LPerryman** [comment]
Blocked until Jenkins can cope with multiple scrapers in single python notebook

**Comment by grace-spitzer-wong** [comment]
Red screen server error message on PMD
