### ISSUE TITLE
GP Practice codes

### ISSUE THREAD

**Issue by grace-spitzer-wong** [GSS-Cogs/family-disability#21]
- [ ] Create pipelines to transform ZIP/CSV direct to PMD for NHS location code mapping.
https://digital.nhs.uk/services/organisation-data-service/data-downloads/gp-and-gp-practice-related-data

https://files.digital.nhs.uk/assets/ods/current/epraccur.zip

**Comment by ajtucker** [comment]
The NHS - Learning Disability Health Check Scheme data uses GP Practice codes for a dimension. We need to have at least a SKOS Concept Scheme to represent this and a SKOS Concept for each practice, along with a label.

The zip file published above contains a PDF and a CSV file. The PDF describes the CSV file and there's quite a bit of information in there that we could potentially represent in RDF.

It may be worth creating a CSV-W JSON-LD file to transform this data into RDF. We could set up a Jenkins job to periodically run the transform and upload to PMD.

**Comment by ajtucker** [comment]
Created a CSV-W JSON file to be used as a direct transform of the CSV to RDF. The resulting RDF uses SKOS, although as this is a flat list of GP practices, there is no hierarchy or top concept. The only info carried across at the moment is code and label.

Added a Jenkins pipeline that downloads the data directly from the above link, unzips and runs csv2rdf.clj to create RDF/Turtle, then uploads and publishes the result on gss-data.org.uk.

Concept Scheme URI is http://gss-data.org.uk/def/concept-scheme/nhs-gp-practices

Concept URIs are http://gss-data.org.uk/def/concept/nhs-gp-practices/{gp_practice_code}

E.g. http://gss-data.org.uk/concept?uri=http%3A%2F%2Fgss-data.org.uk%2Fdef%2Fconcept%2Fnhs-gp-practices%2FA81001

Outstanding questions:
* Does PMD require that SKOS ConceptSchemes have top concepts?
* Does SKOS require this?
* Should we add the SKOS ICs as a test?
* Should we add the rest of the data in the file: address, contact number, details of ownership and transfer, details of status?
